import { Red_Hat_Text } from "next/font/google";
import "./globals.css";
import ProtectedLayout from "@/provider/ProtectedLayout";
import AuthSession from "@/provider/AuthSession";

const redHatText = Red_Hat_Text({
  variable: "--font-red-hat-text",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${redHatText.variable} antialiased`}>
        <AuthSession>
          <ProtectedLayout>{children}</ProtectedLayout>
        </AuthSession>
      </body>
    </html>
  );
}
